In [75]:
import pandas as pd
import numpy as np

In [30]:
# Dataset

data = {
    "Tanggal": [
        "2026-01-03", "2026-01-05", "2026-01-08",
        "2026-01-12", "2026-01-15", "2026-01-18",
        "2026-01-22", "2026-01-25", "2026-01-28",
        "2026-01-30"
    ],
    "Produk": [
        "Laptop", "Mouse", "Keyboard",
        "Laptop", "Monitor", "Mouse",
        "Keyboard", "Laptop", "Monitor", "Mouse"
    ],
    "Kategori": [
        "Elektronik", "Aksesoris", "Aksesoris",
        "Elektronik", "Elektronik", "Aksesoris",
        "Aksesoris", "Elektronik", "Elektronik", "Aksesoris"
    ],
    "Kota": [
        "Surabaya", "Malang", "Surabaya",
        "Jakarta", "Malang", "Jakarta",
        "Surabaya", "Jakarta", "Surabaya", "Malang"
    ],
    "Jumlah": [2, 10, 5, 1, 3, 8, 7, 2, 4, 12],
    "Harga": [8000000, 150000, 300000, 8000000, 2500000,
              150000, 300000, 8000000, 2500000, 150000]
}

df = pd.DataFrame(data)

In [83]:
# 🗺️ QUEST 1 — DATA INSPECTION
print('''==== DATA INSPECTION ====''')

print(f'''info(): 
{df.info()}
\n
head(): 
{df.head()}
\n
tail(): 
{df.tail()}
\n
describe(): 
{df.describe()}
\n
\n
shape(): {df.shape}
\n
missing value: {df.isna().sum().sum()}''')

==== DATA INSPECTION ====
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Tanggal   10 non-null     datetime64[us]
 1   Produk    10 non-null     str
 2   Kategori  10 non-null     str
 3   Kota      10 non-null     str
 4   Jumlah    10 non-null     int64
 5   Harga     10 non-null     int64
 6   Total     10 non-null     int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 692.0 bytes
info():
None


head():
     Tanggal    Produk    Kategori      Kota  Jumlah    Harga     Total
0 2026-01-03    Laptop  Elektronik  Surabaya       2  8000000  16000000
1 2026-01-05     Mouse   Aksesoris    Malang      10   150000   1500000
2 2026-01-08  Keyboard   Aksesoris  Surabaya       5   300000   1500000
3 2026-01-12    Laptop  Elektronik   Jakarta       1  8000000   8000000
4 2026-01-15   Monitor  Elektronik    Malang       3  2500000   7500000


tail():
     Tanggal    Produk    Kategori      Kota  Jumlah    Harga     Total
5 2026-01-18     Mouse   Aksesoris   Jakarta       8   150000   1200000
6 2026-01-22  Keyboard   Aksesoris  Surabaya       7   300000   2100000
7 2026-01-25    Laptop  Elektronik   Jakarta       2  8000000  16000000
8 2026-01-28   Monitor  Elektronik  Surabaya       4  2500000  10000000
9 2026-01-30     Mouse   Aksesoris    Malang      12   150000   1800000


describe():
                   Tanggal     Jumlah         Harga         Total
count                   10  10.000000  1.000000e+01  1.000000e+01
mean   2026-01-16 14:24:00   5.400000  3.005000e+06  6.560000e+06
min    2026-01-03 00:00:00   1.000000  1.500000e+05  1.200000e+06
25%    2026-01-09 00:00:00   2.250000  1.875000e+05  1.575000e+06
50%    2026-01-16 12:00:00   4.500000  1.400000e+06  4.800000e+06
75%    2026-01-24 06:00:00   7.750000  6.625000e+06  9.500000e+06
max    2026-01-30 00:00:00  12.000000  8.000000e+06  1.600000e+07
std                    NaN   3.717825  3.566001e+06  5.920811e+06




shape(): (10, 7)


missing value: 0

In [32]:
# 🧹 QUEST 2 — DATA PREPARATION
print('==== DATA PREPARATION ====')
df['Tanggal'] = pd.to_datetime(df['Tanggal'])
df['Total'] = df['Jumlah'] * df['Harga']
df

==== DATA PREPARATION ====

     Tanggal    Produk    Kategori      Kota  Jumlah    Harga     Total
0 2026-01-03    Laptop  Elektronik  Surabaya       2  8000000  16000000
1 2026-01-05     Mouse   Aksesoris    Malang      10   150000   1500000
2 2026-01-08  Keyboard   Aksesoris  Surabaya       5   300000   1500000
3 2026-01-12    Laptop  Elektronik   Jakarta       1  8000000   8000000
4 2026-01-15   Monitor  Elektronik    Malang       3  2500000   7500000
5 2026-01-18     Mouse   Aksesoris   Jakarta       8   150000   1200000
6 2026-01-22  Keyboard   Aksesoris  Surabaya       7   300000   2100000
7 2026-01-25    Laptop  Elektronik   Jakarta       2  8000000  16000000
8 2026-01-28   Monitor  Elektronik  Surabaya       4  2500000  10000000
9 2026-01-30     Mouse   Aksesoris    Malang      12   150000   1800000

# 🎯 QUEST 3 — DATA ANALYSIS

Jawab pertanyaan berikut menggunakan Pandas:

---

## A. Produk
- Produk apa yang menghasilkan total penjualan terbesar?
- Produk mana yang memiliki jumlah unit terjual terbanyak?

---

In [82]:
produk_total_max = df.groupby('Produk')['Total'].sum().idxmax()
print(produk_total_max)

produk_jumlah_max = df.groupby('Produk')['Jumlah'].sum().idxmax()
print(produk_jumlah_max)

Laptop
Mouse

# Jawaban A:

- Produk yang menghasilkan total penjualan terbesar:
  > Laptop
  
- Produk yang memiliki jumlah unit terjual terbanyak:
  > Mouse

---

# B. Kota
- Kota mana yang menghasilkan **revenue terbesar**?
- Berapa total revenue setiap kota?

---

In [34]:
kota_revenue_max = df.groupby('Kota')['Total'].sum().idxmax()
print(kota_revenue_max)
kota_total_revenue = df.groupby('Kota')['Total'].sum()
print(kota_total_revenue)

Surabaya
Kota
Jakarta     25200000
Malang      10800000
Surabaya    29600000
Name: Total, dtype: int64

# Jawaban B

- Kota yang menghasilkan revenue terbesar:
  > Surabaya
  
- Total Revenue Tiap Kota:
```text
Jakarta   :  25200000
Malang    :  10800000
Surabaya  :  29600000
```

---

# C. Kategori
- Kategori mana yang menghasilkan revenue terbesar?
- Berapa rata-rata `Harga` setiap kategori?

---

In [37]:
kategori_revenue_max = df.groupby('Kategori')['Total'].sum().idxmax()
print(kategori_revenue_max)
kategori_harga_mean = df.groupby('Kategori')['Harga'].mean()
print(kategori_harga_mean)

Elektronik
Kategori
Aksesoris      210000.0
Elektronik    5800000.0
Name: Harga, dtype: float64

# Jawaban C

- Kategori yang menghasilkan revenue terbesar:
  > Elektronik
  
- Rata-Rata Harga setiap Kategori:

```text
Aksesoris   : Rp   210.000
Elektronik  : Rp 5.800.000
```

# D. Statistik Revenue

In [44]:
print(f'''
Rata-Rata Revenue      : {int(df['Total'].mean())}
Total Revenue          : {df['Total'].sum()}
Revenue Terendah       : {df['Total'].min()}
Revenue Tertinggi      : {df['Total'].max()}
Kuartil Tengah Revenue : {int(df['Total'].median())}
''')

Rata-Rata Revenue      : 6560000
Total Revenue          : 65600000
Revenue Terendah       : 1200000
Revenue Tertinggi      : 16000000
Kuartil Tengah Revenue : 4800000

---

In [71]:
# 📊 QUEST 4 — GROUPBY
grouped_1 = df.groupby('Produk', as_index=False)['Jumlah'].sum()
grouped_2 = df.groupby('Produk', as_index=False)['Total'].sum()
grouped_3 = df.groupby('Produk', as_index=False)['Harga'].mean()

df_group_1 = pd.merge(
    grouped_1,
    grouped_2,
    on='Produk'
)
df_group_2 = pd.merge(
    df_group_1,
    grouped_3,
    on='Produk'
)

#rename kolom
df_group_2.columns = ['Produk', 'Total Unit', 'Total Revenue', 'Rata-rata Harga']

#Sorting
sort = df_group_2.sort_values(
    by='Total Revenue',
    ascending=False
)

sort

     Produk  Total Unit  Total Revenue  Rata-rata Harga
1    Laptop           5       40000000        8000000.0
2   Monitor           7       17500000        2500000.0
3     Mouse          30        4500000         150000.0
0  Keyboard          12        3600000         300000.0

In [76]:
# 🔗 QUEST 5 — MERGE / JOIN

# Buat DataFrame Kedua
target = pd.DataFrame({
    "Kota": ["Surabaya", "Malang", "Jakarta"],
    "Target": [10000000, 8000000, 15000000]
})

analisis_kota = df.groupby(
    'Kota', as_index=False
)['Total'].sum()

quest_5 = pd.merge(
    analisis_kota,
    target,
    on='Kota'
)

# rename kolom
quest_5.columns = ['Kota', 'Revenue', 'Target']

# add status
quest_5['Status'] = np.where(
    quest_5['Revenue'] >= quest_5['Target'],
     'Tercapai',
     'Belum Tercapai'
) 
quest_5

       Kota   Revenue    Target    Status
0   Jakarta  25200000  15000000  Tercapai
1    Malang  10800000   8000000  Tercapai
2  Surabaya  29600000  10000000  Tercapai

# 💾 QUEST 6 — IMPORT / EXPORT

dataframe utama:
- df = dataframe mentah.
- sort = dataframe hasil analisis revenue berdasarkan produk.
- quest_5 = dataframe hasil analisis target revenue per kota.

In [80]:
# 💾 QUEST 6 — IMPORT / EXPORT

df.to_csv('capstone_dataframe_mentah.csv', index=False)
sort.to_csv('capstone_dataframe_analyze_1.csv', index=False)
quest_5.to_csv('capstone_dataframe_analyze_2.csv', index=False)

df_mentah = pd.read_csv('capstone_dataframe_mentah.csv')
df_analyze_1 = pd.read_csv('capstone_dataframe_analyze_1.csv')
df_analyze_2 = pd.read_csv('capstone_dataframe_analyze_2.csv')

print(df_mentah)
print('\n'*2)
print(df_analyze_1)
print('\n'*2)
print(df_analyze_2)

      Tanggal    Produk    Kategori      Kota  Jumlah    Harga     Total
0  2026-01-03    Laptop  Elektronik  Surabaya       2  8000000  16000000
1  2026-01-05     Mouse   Aksesoris    Malang      10   150000   1500000
2  2026-01-08  Keyboard   Aksesoris  Surabaya       5   300000   1500000
3  2026-01-12    Laptop  Elektronik   Jakarta       1  8000000   8000000
4  2026-01-15   Monitor  Elektronik    Malang       3  2500000   7500000
5  2026-01-18     Mouse   Aksesoris   Jakarta       8   150000   1200000
6  2026-01-22  Keyboard   Aksesoris  Surabaya       7   300000   2100000
7  2026-01-25    Laptop  Elektronik   Jakarta       2  8000000  16000000
8  2026-01-28   Monitor  Elektronik  Surabaya       4  2500000  10000000
9  2026-01-30     Mouse   Aksesoris    Malang      12   150000   1800000



     Produk  Total Unit  Total Revenue  Rata-rata Harga
0    Laptop           5       40000000        8000000.0
1   Monitor           7       17500000        2500000.0
2     Mouse          30        4500000         150000.0
3  Keyboard          12        3600000         300000.0



       Kota   Revenue    Target    Status
0   Jakarta  25200000  15000000  Tercapai
1    Malang  10800000   8000000  Tercapai
2  Surabaya  29600000  10000000  Tercapai

# 👑 FINAL BOSS — BUSINESS INSIGHT

1. Total Revenue Mencapai sebesar Rp 65.600.000
2. Produk yang menghasilkan penjualan terbesar adalah `Laptop` mencapai Rp 40.000.000.
3. Kota yang menghasilkan Revenue Terbesar merupakan Surabaya sebesar Rp 29.600.000.
4. Semua Cabang kota telah mencapai target penjulan.
5. Rata-rata harga jual kategori Elekronik berada di kisaran Rp 5.800.000.